server:
  port: 8081
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/kk5t/top
          search-paths: config-data